version = 1

[packages."@leourbina/general-coder"]
version = "1.0.3"
resolved = "https://26ac346086d4405f7a976d48747a2a75.r2.cloudflarestorage.com/terrazul-packages-prod/tarballs/leourbina/general-coder/1.0.3.tar.gz"
integrity = "sha256-tSFsvamiCB27C99j630ihjjaHyYMjPzHK0julSZp8vw="
dependencies = { }
yanked = false

[metadata]
generated_at = "2026-01-23T11:43:24.963Z"
cli_version = "0.21.0"
