version = 1

[packages."@leourbina/general-coder"]
version = "1.0.3"
resolved = "https://26ac346086d4405f7a976d48747a2a75.r2.cloudflarestorage.com/terrazul-packages-prod/tarballs/leourbina/general-coder/1.0.3.tar.gz"
integrity = "sha256-tSFsvamiCB27C99j630ihjjaHyYMjPzHK0julSZp8vw="
dependencies = { }
yanked = false

[packages."@terrazul/tdd-engineer"]
version = "1.1.1"
resolved = "https://26ac346086d4405f7a976d48747a2a75.r2.cloudflarestorage.com/terrazul-packages-prod/tarballs/terrazul/tdd-engineer/1.1.1.tar.gz"
integrity = "sha256-K5IVZ0wE2UtGJuk4C1YNQ7PLJnirGB1OocryrP5NjX4="
dependencies = { }
yanked = false

[metadata]
generated_at = "2026-01-28T04:45:05.925Z"
cli_version = "0.21.1"
